### ISSUE TITLE
Transfers on the app should be made through the proxy

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/Xion-hackton#108]
This function https://github.com/chelofinance/Xion-hackton/blob/main/frontend/utils/xion.ts#L26-L84
should make transfers through the proxy.

The msg api of the proxy can be found after this other issue is finished
https://github.com/chelofinance/Xion-hackton/issues/106
@kmchmk as before If you work on this one leave a message on the issue thread. If not ill work on this one

**Comment by kmchmk** [comment]
I haven't done anything for #106 . I can work on it tomorrow, if you haven't.
