### ISSUE TITLE
IBC Relayer by Xion team

### ISSUE THREAD

**Issue by ohadbachner** [chelofinance/Xion-hackton#69]
Hey @rafaelChelo and @kmchmk Xion open for us a IBC channel ( https://docs.burnt.com/xion/nodes-and-validators/become-a-validator/ibc-relayers/xion-testnet-1-less-than-greater-than-injective-888) Please use it.

@srdtrk can it replace the Hermes?

**Comment by rafaelChelo** [comment]
CHanging issue name, since we dont need to create an IBC channel. Just replace the connection ID on all scripts and contracts
