### ISSUE TITLE
Store in global state user vaults

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/Xion-hackton#88]
This hook https://github.com/chelofinance/Xion-hackton/blob/main/frontend/hooks/useMyNFTVaults/index.ts
will load the user vaults. To work the user must be logged in.

Now, when its used in different components it fetches the same vaults. I want the vaults to be stored in state and used across the app. Notice that vaults are *different* from the initial nft table that loads the whole collection, this last componetn should not be affected.

Also, a vault might or might not have any nft on a proposal, so it can raise funds and have 0 nfts to buy.

**Comment by estellechoi** [comment]
can I do this later? I am designing like to see all in Portfolio page (/raising-vault) so probably it will not be reused in other components for demo.

**Comment by rafaelChelo** [comment]
> can I do this later? I am designing like to see all in Portfolio page (/raising-vault) so probably it will not be reused in other components for demo.

Sure, just make sure to not use hardcoded values
