### ISSUE TITLE
Remove keplr wallet connection on nft view

### ISSUE THREAD

**Issue by rafaelChelo** [chelofinance/Xion-hackton#92]
Remove the keplr connection here:
![image](https://github.com/chelofinance/Xion-hackton/assets/99182859/993c1749-8e46-42e1-8781-1555aa1fe756)

Steps and place:
1 - login
2 - Click on nft from table
3 - on nft page keplr appears, remove it since we dont need to do anything on injective (we can do ICA transfers from inj to xion on our side and do stuff only on xion)

**Comment by estellechoi** [comment]
done.
